#!/usr/bin/env python3
"""Build and validate the 69-endpoint Primer/Mega constraint fragments."""

from __future__ import annotations

import argparse
import csv
import io
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MAP_ROOT = ROOT / "plan/ws001-cbus-contract"
CONSTRAINT_ROOT = ROOT / "constraints"

# Sipeed Tang_Primer_20K_SOM-3961_Schematic.pdf, FPGA/connector table.
# Order is exactly platform-endpoints.csv endpoint_index 1..69.
PRIMER_PINS = (
    "K16 J15 H16 H14 G16 H15 F13 G12 J16 H13 J14 J12 G14 H12 G15 G11 "
    "F14 F16 E16 F15 D16 E14 T13 M11 A15 B14 A14 B13 C12 B12 A12 C11 "
    "B11 A11 C9 A9 F10 D11 D10 E10 R16 P15 P16 N15 N16 N14 L16 L14 "
    "K15 K14 M15 L13 M14 K11 K12 K13 E15 D14 L12 J11 T6 P6 T7 R8 T8 "
    "P8 T9 P9 C10"
).split()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def endpoint_port(index: int) -> str:
    if 1 <= index <= 24:
        return f"cbus_ab[{index - 1}]"
    if 25 <= index <= 40:
        return f"cbus_db[{index - 25}]"
    return {
        41: "cbus_ior_n", 42: "cbus_iow_n", 43: "cbus_mrc_n",
        44: "cbus_mwc_n", 45: "cbus_mwe_n", 46: "cbus_bhe_n",
        47: "cbus_reset_n", 48: "cbus_power_n", 49: "cbus_sclk",
        50: "cbus_iordy", 51: "cbus_irq_selected",
        52: "cbus_dack_selected_n", 53: "cbus_drq_selected_n",
        54: "cbus_word_n", 55: "cbus_dmatc_n",
        56: "cbus_b40_exhrq1_n", 57: "cbus_b47_exhrq2_n",
        58: "cbus_b42_exhla1_n", 59: "cbus_b46_exhla2_n",
        60: "cbus_b48_sbusrq", 61: "lvc_data_dir",
        62: "lvc_data_oe_n", 63: "lvc_iordy_oe_n",
        64: "lvc_irq_oe_n", 65: "lvc_word_oe_n",
        66: "lvc_addr_dir", 67: "lvc_addr_oe_n",
        68: "lvc_cmd_dir", 69: "lvc_cmd_oe_n",
    }[index]


def board_rows(board: str) -> list[dict[str, str]]:
    source = read_csv(MAP_ROOT / f"{board}-platform-map.csv")
    assert len(source) == 69
    rows = []
    for offset, item in enumerate(source):
        index = int(item["endpoint_index"])
        assert index == offset + 1
        assert item["io_voltage"] == "3.3V"
        if board == "primer20k":
            location = PRIMER_PINS[offset]
            evidence = "Tang_Primer_20K_SOM-3961_Schematic.pdf"
        else:
            match = re.fullmatch(r"BANK[234]_([A-Z]{1,2}[0-9]{1,2})_IO[RB][0-9]+[AB]", item["module_net"])
            assert match, item["module_net"]
            location = match.group(1)
            evidence = "tang_mega_138k_30353_Schematics.pdf sheet 6"
        rows.append({
            "endpoint_index": str(index),
            "port": endpoint_port(index),
            "location": location,
            "connector": item["connector"],
            "connector_pin": item["connector_pin"],
            "module_net": item["module_net"],
            "bank": item["bank"],
            "io_type": "LVCMOS33",
            "source": evidence,
        })
    return rows


def render_manifest(rows: list[dict[str, str]]) -> str:
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=rows[0].keys(), lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()


def render_cst(board: str, rows: list[dict[str, str]]) -> str:
    clock_pin = "H11" if board == "primer20k" else "V22"
    lines = [
        f"// Generated by {Path(__file__).relative_to(ROOT)}; do not edit by hand.",
        "// This is a pin fragment, not proof of electrical or timing closure.",
        f'IO_LOC "board_clk" {clock_pin};',
        'IO_PORT "board_clk" IO_TYPE=LVCMOS33 PULL_MODE=NONE;',
        "",
    ]
    for row in rows:
        lines.append(f'IO_LOC "{row["port"]}" {row["location"]};')
        lines.append(f'IO_PORT "{row["port"]}" IO_TYPE=LVCMOS33 PULL_MODE=NONE;')
    return "\n".join(lines) + "\n"


def expected_files() -> dict[Path, str]:
    result = {}
    for board in ("primer20k", "mega138k"):
        rows = board_rows(board)
        directory = CONSTRAINT_ROOT / board
        result[directory / "cbus-endpoints.csv"] = render_manifest(rows)
        result[directory / "cbus.cst"] = render_cst(board, rows)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected_files()
    if args.check:
        for path, expected in files.items():
            actual = path.read_text(encoding="utf-8")
            assert actual == expected, f"stale generated file: {path.relative_to(ROOT)}"
    else:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("PASS: Primer/Mega 69-endpoint constraints")


if __name__ == "__main__":
    main()
